#!/bin/sh

set -a; for FILE in /etc/environment /etc/environment.d/*.conf; do [ -e "$FILE" ] && . "$FILE"; done; set +a
[ $# -lt 1 ] && set -- sh
[ $$ -eq 1 ] && set -- /usr/bin/tini -- /etc/init "$@"
exec "$@"